version: '3.8'

services:
  web:
    build: .
    container_name: fastapi_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env   # Load the environment variables from the .env file
    environment:
      - DATABASE_URL=${DATABASE_URL}   # Ensure FastAPI gets the correct DATABASE_URL
    networks:
      - fastapi_network

  db:
    image: postgres:13
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env   # Use environment variables from the .env file
    networks:
      - fastapi_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - fastapi_network

networks:
  fastapi_network:

volumes:
  postgres_data:
